name: Build

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup NPM
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: Install Strapi dependencies
        run: npm ci
        working-directory: ./resume-strapi

      - name: Start Strapi
        run: npm run start-fork --if-present
        working-directory: ./resume-strapi

      - name: Install Svelte/Sapper dependencies
        run: npm ci
        working-directory: ./resume-sapper

      - name: Build Svelte/Sapper
        run: npm run export --if-present
        working-directory: ./resume-sapper
