name: Resume

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      STORAGE_ACCOUNT_KEY: ${{ secrets.STORAGE_ACCOUNT_KEY }}
      STORAGE_ACCOUNT_NAME: resumesapper
      STORAGE_CONTAINER_NAME: $web

    steps:
      - uses: actions/checkout@v2

      - name: Setup NPM
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: Install Strapi dependencies
        run: npm ci
        working-directory: ./resume-strapi

      # - name: Start Strapi
      #   run: npm run start-fork --if-present
      #   working-directory: ./resume-strapi

      - name: Install Svelte/Sapper dependencies
        run: npm ci
        working-directory: ./resume-sapper

      - name: Build Svelte/Sapper
        run: npm run export --if-present
        working-directory: ./resume-sapper

      - name: Deploy
        if: github.event_name == 'push'
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: |
            az storage blob delete-batch -s '${{ env.STORAGE_CONTAINER_NAME }}' --account-name ${{ env.STORAGE_ACCOUNT_NAME }} --account-key ${{ env.STORAGE_ACCOUNT_KEY }}
            az storage blob upload-batch -s 'resume-sapper/__sapper__/export' -d '${{ env.STORAGE_CONTAINER_NAME }}' --account-name ${{ env.STORAGE_ACCOUNT_NAME }} --account-key ${{ env.STORAGE_ACCOUNT_KEY }}
