# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Resume

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    env:
      STORAGE_ACCOUNT_KEY: ${{ secrets.STORAGE_ACCOUNT_KEY }}
      STORAGE_ACCOUNT_NAME: resumesapper
      STORAGE_CONTAINER_NAME: $web

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup NPM
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build 
      run: npm run export --if-present

    - name: Deploy
      if: github.event_name == 'push'
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
          az storage blob delete-batch -s '${{ env.STORAGE_CONTAINER_NAME }}' --account-name ${{ env.STORAGE_ACCOUNT_NAME }} --account-key ${{ env.STORAGE_ACCOUNT_KEY }}
          az storage blob upload-batch -s '__sapper__/export' -d '${{ env.STORAGE_CONTAINER_NAME }}' --account-name ${{ env.STORAGE_ACCOUNT_NAME }} --account-key ${{ env.STORAGE_ACCOUNT_KEY }}
